version: "3.7"

services:
  selenium-hub:
    image: selenium-hub-custom
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - SE_GRID_TIMEOUT=30000 # Optional grid timeout configuration
    networks:
      - selenium-grid

  chrome-node:
    image: docker-10032-repo.repo.devops.poalim.bank/selenium/node-chrome:4.25.0-20240922
    container_name: chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_STEREOTYPES={"browserName":"chrome","se.tags":["GENERIC"]}
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
