name: Run Python Script

on:
  #schedule:
  #  - cron: '42 21 * * *' # Runs every day at midnight UTC
  push:
    branches:
      - dev
#
jobs:
  selenium-hub-setag-cd:
    runs-on: ubuntu-latest
    env:
      sel_version: "4.14.1"
    steps:
        # Step 1: Check out the repository
        - name: Checkout code
          uses: actions/checkout@v3
        # Step 2: Set up JDK (Java Development Kit)
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin' # Use Eclipse Temurin distribution
            java-version: '17' # Specify Java version
        # Step 3: Cache Maven dependencies for faster builds
        - name: Cache Maven dependencies
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-

        # Step 4: Build the project with Maven
        - name: Build with Maven
          run: mvn clean package